//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.19 at 03:17:43 PM CST 
//


package animal;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the animal package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Animal_QNAME = new QName("www.davenkin.common", "animal");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: animal
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Animal }
     * 
     */
    public Animal createAnimal() {
        return new Animal();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Animal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "www.davenkin.common", name = "animal")
    public JAXBElement<Animal> createAnimal(Animal value) {
        return new JAXBElement<Animal>(_Animal_QNAME, Animal.class, null, value);
    }

}
